#!/bin/bash
Modified from http://www.devdaily.com/blog/post/java/shell-script-search-search-multiple-jar-files-class-pattern  
# Usage: searchjars.sh com/whatever/classnametogrepfor rootdir  
LOOK_FOR=$1

for i in `find $2 -name "*jar"` 
do   
  echo "Looking in $i ..."   
  jar tvf $i | grep $LOOK_FOR > /dev/null   
  if [ $? == 0 ]   
  then
    echo "==> Found \"$LOOK_FOR\" in $i"   
  fi
done
